#ifndef __STATUS_INCLUDED__
#define __STATUS_INCLUDED__

typedef enum _Status_t
{
	STATUS_OK = 0,
	STATUS_OK_GAME_UPDATE_STARTED,
	STATUS_OK_GAME_UPDATE_COMPLETED,
	STATUS_OK_NOT_PROCESSED,
	STATUS_OK_PROCESSED,
	STATUS_OK_TAB_NO_HANDLER,
	STATUS_OK_EMPTY_DATASET,


	STATUS_ERR = 1000,
	STATUS_ERR_WINDOW_CANNOT_REGISTER,
	STATUS_ERR_WINDOW_CANNOT_CREATE,
	STATUS_ERR_WINDOW_CANNOT_POPULATE,
	STATUS_ERR_BOT_SYNTAX_ERROR,
	STATUS_ERR_GAME_UPDATE_NOT_IN_PROGRESS,
	STATUS_ERR_GAME_UPDATE_IN_PROGRESS,
	STATUS_ERR_NOT_ENOUGH_ROOM,
	STATUS_ERR_TAB_NO_HANDLER,
	STATUS_ERR_FILE_CANNOT_OPEN,
	STATUS_ERR_FILE_CANNOT_READ,
	STATUS_ERR_FILE_WRONG_FORMAT,
	STATUS_ERR_DATA_INVALID,
	STATUS_ERR_NO_SUCH_TEAM,
	STATUS_ERR_TEAM_ALREADY_EXISTS,
} Status_t;

#endif